export const partData = [
  {
    category: `Coin Op`,
    subcategory: `Coin Slides`,
    partNumber: `27-35-000-125`,
    description: `V5 Coin Slide Pre Set, $1.25`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Slides`,
    partNumber: `27-35-000-150`,
    description: `V5 Coin Slide Pre Set, $1.50`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Slides`,
    partNumber: `27-35-000-175`,
    description: `V5 Coin Slide Pre Set, $1.75`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Slides`,
    partNumber: `27-35-000-200`,
    description: `V5 Coin Slide Pre Set, $2.00`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `8-1150`,
    description: `UG400 (4" Long)`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `8-1170`,
    description: `UG800 (5.875" x 3.515" x 3.175")`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `8-1170-KA`,
    description: `UG801 Keyed Alike (5.875" x 3.515" x 3.175")`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `8-1210`,
    description: `UG400A (5.5" x 3.515" x 2.375")`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `8-1210-KA`,
    description: `UG400A Keyed Alike (5.5" x 3.515" x 2.375")`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `TJ0400ET`,
    description: `Door Lock & Key Set`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Slides`,
    partNumber: `TJ21771`,
    description: `Spring, ESD/GW`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `TJGR800`,
    description: `Door Access Key`,
  },
  {
    category: `Coin Op`,
    subcategory: `Coin Boxes`,
    partNumber: `WG04L01556`,
    description: `Chute Bolt (WH65M11)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `4317824`,
    description: `5' Power Cord Kit (Incl. cord lock & marrettes, straight plug)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJ60663`,
    description: `6' Power Cord, 90° Angled Plug`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJ69-6C`,
    description: `Elbow, 3/8" - 3/8"`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `W10685193`,
    description: `Elbow Hose Fitting, 3/4" x 3/8" Whirlpool`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJ65447LF`,
    description: `Elbow Brass Adapter 3/8" Comp Fitting x 3/4" FHT (WPL Dishwashers 2009 & Newer)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJ90262`,
    description: `Straight and Manual Shut Off Valve Set`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJSSDW7`,
    description: `7' Universal Drain Hose`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJB150`,
    description: `50' Drain Hose`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJB6350`,
    description: `50' Dishwasher Drain Hose, Bulk Roll, 5/8" OD`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJ511-QG3-31`,
    description: `Dual Outlet Straight Valve, 1/2" Quick Grip x 3/8" OD`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Installation`,
    partNumber: `TJ60657`,
    description: `36" Angle Pigtail`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Misc`,
    partNumber: `80515`,
    description: `Dishwasher Salt`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Misc`,
    partNumber: `00579532`,
    description: `Dishwasher Salt`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Misc`,
    partNumber: `C-DM06N`,
    description: `Dishwasher Magic`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Misc`,
    partNumber: `W10320829`,
    description: `Dishwasher Salt`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ48747`,
    description: `48" Dishwasher Water Line, Braided Stainless Steel 3/8" x 3/8" Fitting`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ48376`,
    description: `48" Stainless Steel Hose, 90° Elbow`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ48364`,
    description: `60" Dishwasher Water Line, Braided Stainless Steel 3/8" x 3/8" Fitting`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ48377`,
    description: `60" Stainless Steel Hose, 90° Elbow`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ4066282`,
    description: `72" Dishwasher Installation Kit, Stainless Steel Water Line w/2 Fittings & Tap`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ41045`,
    description: `72" Dishwasher Water Line, Braided Stainless Steel 3/8" x 3/8" & 3/8" x 3/4" Fitting`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ48365`,
    description: `72" Dishwasher Water Line, Braided Stainless Steel 3/8" x 3/8" Fitting`,
  },
  {
    category: `Dishwasher`,
    subcategory: `Water Lines`,
    partNumber: `TJ48366`,
    description: `96" Dishwasher Water Line, Braided Stainless Steel 3/8" x 3/8" Fitting`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DW7601`,
    description: `Door Gasket (154827601)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DW4001`,
    description: `Door Link Kit (8194001)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DW26401`,
    description: `Drain Pump (A00126401)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `WV10014`,
    description: `Inlet Valve (WD15X10014)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DW2394`,
    description: `Rack Adjuster (W10712394)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DW1001`,
    description: `Splash Shield Kit (154701001)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DW3762`,
    description: `Thermal Cutout (8193762)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DW8275`,
    description: `Thermal Fuse (W10258275)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `WV3601`,
    description: `Water Valve (154513601)`,
  },
  {
    category: `Dishwasher`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `WV8389`,
    description: `Water Valve (W10158389)`,
  },
  {
    category: `Dryer`,
    subcategory: `Aluminum Flex Venting`,
    partNumber: `TJA048/40`,
    description: `Aluminum Flex Venting, 4" x 8' (MFX48)`,
  },
  {
    category: `Dryer`,
    subcategory: `Aluminum Flex Venting`,
    partNumber: `TJF0408B`,
    description: `Super Flex Aluminum Dryer Vent, 4" x 8'`,
  },
  {
    category: `Dryer`,
    subcategory: `Aluminum Flex Venting`,
    partNumber: `TJF0425`,
    description: `Aluminum Flex Venting, 4" x 25'`,
  },
  {
    category: `Dryer`,
    subcategory: `Aluminum Flex Venting`,
    partNumber: `TJF0450`,
    description: `Aluminum Flex Venting, 4" x 50'`,
  },
  {
    category: `Dryer`,
    subcategory: `Aluminum Flex Venting`,
    partNumber: `TJMFX410`,
    description: `Aluminum Flex Venting, 4" x 10'`,
  },
  {
    category: `Dryer`,
    subcategory: `Ignitors`,
    partNumber: `TJSDE350`,
    description: `Dryer Ignitor (4392003, WE4X444, 5304440277)`,
  },
  {
    category: `Dryer`,
    subcategory: `Ignitors`,
    partNumber: `TJSDE358`,
    description: `Dryer Ignitor (WE4X739, 134394900, 134192000)`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJWS5SSSTM`,
    description: `Stainless Steel Steam Dryer Installation Kit`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJ41024`,
    description: `Steam Dryer Hose Installation Kit, Black Rubber`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJ41025`,
    description: `Steam Dryer Hose Installation Kit, Braided Stainless Steel`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJDAF2`,
    description: `4" Skinny Duct Aluminum Dryer Vent (Adjustable 27" - 48" Oval Duct)`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJHUPK8F`,
    description: `Installation Kit, 8' Flexible Aluminum Vent w/2 Hook-Ups`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJLTF`,
    description: `Indoor Dryer Vent Kit (2 Clamps, 60" Aluminum Vent & Anti-Tip Bucket)`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `41006`,
    description: `Chrome Y Connector for Steam Dryers`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJDE904`,
    description: `4" Aluminum Elbow, Adjustable 90° Heavy Gauge`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJRVHAW4/18`,
    description: `4" Wide Mouth Vent Hood w/Bird Guard, White`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJSVHAW4/18`,
    description: `4" Louvered Vent Hood, White`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `FC0408B`,
    description: `4" Dryer Duct, Fire Resistant`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJBD04`,
    description: `Cold Draft Blocker`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJRLE202`,
    description: `Lint Eater Kit (DVC202)`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJUBGW`,
    description: `Universal Bird Guard (PB10)`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJHUP`,
    description: `Upper Protector, 4"`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJMCX4`,
    description: `4" Worm Clamp`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJMSC4100`,
    description: `4" Metal Spring Clamp`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJMC450`,
    description: `4" Metal Clamp Worm Drive (MC4)`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJP430`,
    description: `Round Aluminum Pipe, 4" x 24" Heavy Gauge Aluminum`,
  },
  {
    category: `Dryer`,
    subcategory: `Installation`,
    partNumber: `TJ44150`,
    description: `Dryer Cord (544150)`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `20C-3131-48`,
    description: `48"  Coated Gas Dryer & Water Heater Connector, 1/2" MIP x 1/2" MIP`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `20C-3131-60`,
    description: `60" Coated Gas Dryer & Water Heater Connector, 1/2" MIP x 1/2" MIP`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `20C-3131-72`,
    description: `72" Coated Gas Dryer & Water Heater Connector, 1/2" MIP x 1/2" MIP`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `20C-3132-48`,
    description: `48" Coated Gas Dryer & Water Heater Connector, 1/2" MIP x 1/2" FIP`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `20C-3132-60`,
    description: `60" Coated Gas Dryer & Water Heater Connector, 1/2" MIP x 1/2" FIP`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `20C-3132-72`,
    description: `72" Coated Gas Dryer & Water Heater Connector, 1/2" MIP x 1/2" FIP`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `TJ20-3132-48`,
    description: `48" Uncoated Dryer Connector, 1/2" OD (1/2" F x 1/2" M - Tapped 3/8" FIP)`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `TJ20-3132-60`,
    description: `60" Uncoated Dryer Connector, 1/2" OD (1/2" F x 1/2" M - Tapped 3/8" FIP)`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `TJ20-3132-72`,
    description: `72" Uncoated Dryer Connector, 1/2" OD (1/2" F x 1/2" M - Tapped 3/8" FIP)`,
  },
  {
    category: `Dryer`,
    subcategory: `Stainless Steel Dryer & Furnace Gas Connectors`,
    partNumber: `TJ20C-3232-24`,
    description: `24"  Coated Gas Dryer & Water Heater Connector, 1/2" MIP x 1/2" FIP`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJCF20FB`,
    description: `20A Ceramic Fuse, Fast Blow`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJGAB15BP`,
    description: `15A 250V Microwave Fuse (14QBP0238)`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJGP15`,
    description: `15A Fuse`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJGP20`,
    description: `20A Fuse`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJGP25`,
    description: `25A Fuse`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJGP30`,
    description: `30A Fuse (RE1030P)`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJNRN15-1`,
    description: `15A Fuse Cartridge`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJNRN20-1`,
    description: `20A Fuse Cartridge (NRN201C)`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJNRN30-1`,
    description: `30A Fuse Cartridge (NRN301C)`,
  },
  {
    category: `Electrical`,
    subcategory: `Fuses`,
    partNumber: `TJNRN40-1`,
    description: `40A Fuse Cartridge`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES15202`,
    description: `250V Range Pilot Light Assembly, Red Lens/Flush Mount`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES15501`,
    description: `125V Pilot Light Assembly, Red Lens`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES16100`,
    description: `Dryer/Dishwasher Switch (16300)`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES16300`,
    description: `Dryer/Dishwasher Switch (16300)`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES16301`,
    description: `Dryer/Dishwasher Switch (16301)`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES16600`,
    description: `Dryer/Dishwasher Switch (16600)`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES16802`,
    description: `Micro Switch (16802)`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES18805`,
    description: `Refrigerator/Freezer Fan Switch (18805)`,
  },
  {
    category: `Electrical`,
    subcategory: `Switches`,
    partNumber: `TJES18814`,
    description: `Fan and Light Switch (18814)`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TB123A`,
    description: `Spanner Wrench`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ17-132`,
    description: `Sil-Glyde Lubricant, 1.5 oz.`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ3107`,
    description: `Flux, 7oz.  (60-515)`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJAC302M`,
    description: `2m Extension Cord, A/C Rated`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJT1151C`,
    description: `Marrettes, Orange (100-pack, #18 - #14 AWG)`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `KD-145`,
    description: `Hose Pinch Off Pliers`,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJ450040`,
    description: `Duct Tape, 2" x 60 yds (DT488S)`,
  },
  {
    category: `Misc`,
    subcategory: `Ball Valves`,
    partNumber: `TJ10737`,
    description: `Ball Valve, 1/4" x 1/2" (P161340)`,
  },
  {
    category: `Misc`,
    subcategory: `Ball Valves`,
    partNumber: `TJ10738`,
    description: `Ball Valve, 3/8" x 1/2"`,
  },
  {
    category: `Misc`,
    subcategory: `Ball Valves`,
    partNumber: `TJBV4046-8D`,
    description: `Ball Valve, 1/2 Tube 1/2P`,
  },
  {
    category: `Misc`,
    subcategory: `Ball Valves`,
    partNumber: `TJBV4103-D`,
    description: `Ball Valve (605200005)`,
  },
  {
    category: `Misc`,
    subcategory: `Ball Valves`,
    partNumber: `TJBV2103-D-CGA`,
    description: `Gas Ball Valve, 1/2F - 1/2F (605000005)`,
  },
  {
    category: `Misc`,
    subcategory: `Capacitors`,
    partNumber: `92029`,
    description: `Oval Dual Run Capacitor 15+10 MFD x 370 VAC`,
  },
  {
    category: `Misc`,
    subcategory: `Capacitors`,
    partNumber: `TJ12018`,
    description: `Capacitor, 35 uF MFD x 370 VAC`,
  },
  {
    category: `Misc`,
    subcategory: `Capacitors`,
    partNumber: `TJ12072`,
    description: `Capacitor, 35 + 5 uF MFD x 370 VAC (36-35-5-3744)`,
  },
  {
    category: `Misc`,
    subcategory: `Capacitors`,
    partNumber: `TJ12164`,
    description: `Capacitor, 20/15 MFD x 370 VAC`,
  },
  {
    category: `Misc`,
    subcategory: `Capacitors`,
    partNumber: `TJCS216-259X330`,
    description: `Start Capacitor, 216 - 259 MFD/330VAC`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ1-22-12-000`,
    description: `TVM Multi-Purpose Silicone, Clear`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ1-24-12-003`,
    description: `TVM High Temperature Silicone, Red Cartridge`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ70130`,
    description: `White Lithium Grease`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ70131`,
    description: `Lith-Ease, 8oz (17-131)`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ79036`,
    description: `8oz WD-40, Smart Straw`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ79037`,
    description: `11oz WD-40, Smart Straw`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJHS22008`,
    description: `Bubble Leak Detector`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `MO44`,
    description: `Rust Buster`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `MO98`,
    description: `Lubricating Oil`,
  },
  {
    category: `Misc`,
    subcategory: `Chemicals`,
    partNumber: `TJ1-41-12-001`,
    description: `Bull Seal, Multi-Fix Adhesive & Sealant`,
  },
  {
    category: `Misc`,
    subcategory: `Clamps`,
    partNumber: `TJ10`,
    description: `Clamp, 10 1/2" - 1 1/8"  (79312, HS10)`,
  },
  {
    category: `Misc`,
    subcategory: `Clamps`,
    partNumber: `TJ24`,
    description: `Clamp, 1" - 2" (79328)`,
  },
  {
    category: `Misc`,
    subcategory: `Clamps`,
    partNumber: `TJ12`,
    description: `Clamp, 9/16" - 1 1/4" (79332)`,
  },
  {
    category: `Misc`,
    subcategory: `Clamps`,
    partNumber: `TJ16`,
    description: `Clamp 11/16" X 1 1/2"  (79333, HS16)`,
  },
  {
    category: `Misc`,
    subcategory: `Clamps`,
    partNumber: `TJ20`,
    description: `Clamp, 20 7/8" - 1/ 3/4" (79334, HS20)`,
  },
  {
    category: `Misc`,
    subcategory: `Clamps`,
    partNumber: `4`,
    description: `Micro Clamp, 7/32" - 5/8" (79340)`,
  },
  {
    category: `Misc`,
    subcategory: `Clamps`,
    partNumber: `60423`,
    description: `Clamp, Disposal Connector`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `80527`,
    description: `Limefresh Dishwasher Cleaner, 750g`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ106`,
    description: `Daily Cooktop Cleaner, 22oz Trigger`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ15-C13532`,
    description: `Spray Nine Industrial Cleaner/Degreaser, 946ml`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ1641`,
    description: `Weinman Stainless Steel Cleaner, 12oz Aerosol`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ2088C`,
    description: `Goo Gone, 8oz`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ3055`,
    description: `Stainless Steel Magic, 14oz Trigger`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ3057`,
    description: `Stainless Steel Magic, 24oz Trigger`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ3060`,
    description: `Stainless Steel Magic, 30 Wipes`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ3061`,
    description: `Stainless Steel Magic Glass Cooktop Cleaner & Polish, 16oz Bottle`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ3062`,
    description: `Stainless Steel Magic, 17oz Aerosol`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ328`,
    description: `Appliance Cleaner, 16oz Trigger`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ331`,
    description: `BBQ Grill Cleaner. 24oz Trigger`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ37`,
    description: `Glass Cooktop Cleaner, 460ml Bottle`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ38C`,
    description: `Glass Cooktop Cleaner, 230ml Bottle`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ45`,
    description: `Cooktop Scrubbing Pads`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ49`,
    description: `Stainless Steel Cleaner & Polish, 17oz Aerosol`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ67`,
    description: `BBQ Cleaning Pad`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ69`,
    description: `Gas Range Cleaning Pad`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ70`,
    description: `Daily Cooktop Cleaner, 12oz Trigger`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ76`,
    description: `Stainless Steel Cleaner & Polish, 12oz Trigger`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ79026`,
    description: `Red Cloth Shop Towels, 12 per Bag`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ9`,
    description: `Granite Cleaner & Polish, 8oz Bottle`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ90`,
    description: `Cooktop Wipes, 30 Count`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJ92`,
    description: `Stainless Steel Wipes, 30 Count`,
  },
  {
    category: `Misc`,
    subcategory: `Cleaners`,
    partNumber: `TJWEIMWIPES`,
    description: `Weinman Stainless Steel Wipes`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ50099`,
    description: `Aluminum Foil Tape, 2” x 50 yds`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ711503`,
    description: `5% Silfos Rods, 1 lb. (60-092)`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ83104`,
    description: `Shubee Shoe Covers (50/box)`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJIG-1090`,
    description: `Universal Furnace Ignitor Kit`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJK701M`,
    description: `1m Jumbo Appliance Cord (547210)`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `86706`,
    description: `Waste King 1/2 HP Food Waste Disposer`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `5304469950`,
    description: `Food Grade Silicone Sealant`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ50033`,
    description: `Teflon Tape Gas Yellow`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ50059`,
    description: `Black Electrical Tape`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ40A15`,
    description: `40W Appliance Bulb (A15)`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ86700`,
    description: `1/3 HP Disposer`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJLA-41600`,
    description: `Silc-Tite Stik, 1.25oz`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJMA-25882`,
    description: `Orange Wire Connector, 100P`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJMA-PT160`,
    description: `Pocket Thermometer`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJMA-PT160B`,
    description: `1" Pocket Thermometer Blister Pk`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJMA-PT550`,
    description: `Pocket Thermometer`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `DM10T`,
    description: `Economy Dig Multimeter w/Temperature`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `PL6`,
    description: `Stick Light`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ50157`,
    description: `14" Nylon Ties, 50/pkg`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `20378`,
    description: `1/8" Air Valve Radiator Angle`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ72218`,
    description: `Thermocouple, 18" (For Hot Water Heaters, Furnaces) `,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ72230`,
    description: `Thermocouple, 30" (For Hot Water Heaters, Furnaces) `,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `TJ72236`,
    description: `Thermocouple, 36" (For Hot Water Heaters, Furnaces) `,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJ42009`,
    description: `Thread Sealant, Slic-Tite Paste 1/4 pt. (For Water, Air, Steam, Natural Gas, LP Gas, Refrigerants)`,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJ50011`,
    description: `Teflon Tape`,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJMA-322-2`,
    description: `Aluminum Tape, 2" x 50 yds`,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJCT-3X50`,
    description: `3/16" x 50' Copper (200005001)`,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJCT-4X50`,
    description: `1/4" x 50' Copper (200005000)`,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJCT-5X50`,
    description: `5/16" x 50' (200005003)`,
  },
  {
    category: `Misc`,
    subcategory: `Installation`,
    partNumber: `TJCT-6X50`,
    description: `3/8" x 50' Copper`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `T1111C`,
    description: `High Temperature Female Slip-Ons (100pc)`,
  },
  {
    category: `Misc`,
    subcategory: `General`,
    partNumber: `T1112C`,
    description: `High Temperature Female Slip-Ons (100pc)`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Butt Connectors`,
    partNumber: `T1051`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Butt Connectors`,
    partNumber: `T1051C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Butt Connectors`,
    partNumber: `T1052`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Butt Connectors`,
    partNumber: `T1052C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Butt Connectors`,
    partNumber: `T1053`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Butt Connectors`,
    partNumber: `T1053C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1056`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1056C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1057`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1057C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1058`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1058C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1059`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Closed End Connectors`,
    partNumber: `T1059C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T1001`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T1001C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T1002 `,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T1002C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T2002`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T2002C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T2004`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Insulated Female Slip-Ons`,
    partNumber: `T2004C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-12821`,
    description: `Watt Meter`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-12835`,
    description: `Digital Manometer`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-16550`,
    description: `Infared Thermometer`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-600CFA`,
    description: `Auto Ranging Economy`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-9355`,
    description: `Nut Driver, Set In Pouch`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-DM1`,
    description: `Mini Digital Multimeter`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-DMTK`,
    description: `Auto Ranging Economy`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-OVN1`,
    description: `Oven Thermometer, 150 - 550`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA-RT330`,
    description: `Digital Stem Thermometer`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA02653-2`,
    description: `Terminal Kit`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `TJMA06295P`,
    description: `Wire Connectors In Plastic`,
  },
  {
    category: `Misc`,
    subcategory: `Multimeters`,
    partNumber: `MA-12816`,
    description: `Analog Multimeter w/Test Leads`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `TJ65234`,
    description: `60PT-4 Plastic Sleeve`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1150`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1150C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1151`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1151C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1152`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1152C`,
    description: `100pc`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1153`,
    description: `20pc`,
  },
  {
    category: `Misc`,
    subcategory: `Wire Connectors - Plastic`,
    partNumber: `T1153C`,
    description: `100pc`,
  },
  {
    category: `Range`,
    subcategory: `Ignitors`,
    partNumber: `TJSGR1321`,
    description: `Ignitor (WB13K21)`,
  },
  {
    category: `Range`,
    subcategory: `Ignitors`,
    partNumber: `TJSGR4001`,
    description: `Ignitor (PB04001)`,
  },
  {
    category: `Range`,
    subcategory: `Ignitors`,
    partNumber: `TJSGR403`,
    description: `Round Ignitor (4342528)`,
  },
  {
    category: `Range`,
    subcategory: `Ignitors`,
    partNumber: `TJSGR414`,
    description: `Flat Ignitor (12400035)`,
  },
  {
    category: `Range`,
    subcategory: `Infinite Switches`,
    partNumber: `812608`,
    description: `Universal Infinite Switch (WP3149400, MOQ 200)`,
  },
  {
    category: `Range`,
    subcategory: `Infinite Switches`,
    partNumber: `TJ6500-208`,
    description: `Universal Infinite Switch, Horizontal Flat Shaft`,
  },
  {
    category: `Range`,
    subcategory: `Infinite Switches`,
    partNumber: `TJ6500-209`,
    description: `Universal Infinite Switch, Vertical Flat Shaft`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJA316222201`,
    description: `6" Universal Black Ring/Pan`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJA316222301`,
    description: `8" Universal Black Ring/Pan`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJCP6-2C`,
    description: `6" Chrome Drip Bowl, Maytag Style`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJCRI6`,
    description: `6" Universal Chrome Ring`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJCRI8`,
    description: `8" Universal Chrome Ring`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJCRP6`,
    description: `6" Universal Chrome Ring/Pan`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJCRP8`,
    description: `8" Universal Chrome Ring/Pan`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJMS6-EN2`,
    description: `6" Black Porcelain Pan`,
  },
  {
    category: `Range`,
    subcategory: `Rings & Bowls`,
    partNumber: `TJMS9-EN2`,
    description: `8" Black Porcelain Pan`,
  },
  {
    category: `Range`,
    subcategory: `Stainless Steel Gas Range Connectors`,
    partNumber: `30C-3135-48`,
    description: `48" Range & Furnace Connector, 1/2" MIP x 1/2" FIP w/Ball Valve`,
  },
  {
    category: `Range`,
    subcategory: `Stainless Steel Gas Range Connectors`,
    partNumber: `30C-3141-48`,
    description: `48" Range & Furnace Connector, 1/2" MIP x 3/4" MIP`,
  },
  {
    category: `Range`,
    subcategory: `Stainless Steel Gas Range Connectors`,
    partNumber: `30C-3141-60`,
    description: `60" Range & Furnace Connector, 1/2" MIP x 3/4" MIP`,
  },
  {
    category: `Range`,
    subcategory: `Stainless Steel Gas Range Connectors`,
    partNumber: `30C-3141-72`,
    description: `72" Range & Furnace Connector, 1/2" MIP x 3/4" MIP`,
  },
  {
    category: `Range`,
    subcategory: `Stainless Steel Gas Range Connectors`,
    partNumber: `TJ30-3141-48`,
    description: `48" Uncoated Range Connector, 5/8" OD (1/2" M x 3/4" M)`,
  },
  {
    category: `Range`,
    subcategory: `Stainless Steel Gas Range Connectors`,
    partNumber: `TJ30-3141-60`,
    description: `60" Uncoated Range Connector, 5/8 OD (1/2" M x 3/4" M)`,
  },
  {
    category: `Range`,
    subcategory: `Stainless Steel Gas Range Connectors`,
    partNumber: `TJ30-3141-72`,
    description: `72" Uncoated Range Connector, 5/8 OD (1/2" M x 3/4" M)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `MTP13TYA`,
    description: `6", 1300w/240v (21153.006, W112555551)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `MTP21TYA`,
    description: `8", 2150w/240v (21153.008, W112555552)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-021`,
    description: `6", 1500/1125w, 240/208v`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-033`,
    description: `8", 2100w, 240v`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-140`,
    description: `6" 1500w Spade Style, (P1T15F, WB17M146 Block)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-151`,
    description: `8", 2400w (P1T15F)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-187`,
    description: `6", 1000w, 120V`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-216`,
    description: `8", 2100w (MC-21B)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-219`,
    description: `6" 1250w, Utility`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-815`,
    description: `6", 1500w (PW1C15HT, PS15-4)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-821`,
    description: `8", 2100w (PW1C21HT, PS21-4)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-824`,
    description: `8", 2400w (PW1C24HT, PS240-4)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJ38-826`,
    description: `8", 2600w (PS26-4BK, PS26-4)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJMP15MA`,
    description: `6" 1500W, Loop Style Delta Frame (1430306K Block)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJMP21MA`,
    description: `8" 2100w, (TS5D8221PB)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJMP21YA`,
    description: `8", 2100w (660533)`,
  },
  {
    category: `Range`,
    subcategory: `Universal Surface Elements`,
    partNumber: `TJMP26MA`,
    description: `8" 2600W Loop Style Delta Frame (1430306K Block)`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `319000009`,
    description: `Cooktop Cleaning Kit`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `6700S0011`,
    description: `Electric Thermostat Kit`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJ1372B`,
    description: `Appliance Outlet, Black`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJ1372W`,
    description: `Appliance Outlet, White`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJ24HP-01-1`,
    description: `Oven Thermometer (124)`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJ44147`,
    description: `Range Cord 4', 50 Amp`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJ48301`,
    description: `Gas Range Outlet Adapter, 220v to 110v`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJ72171K`,
    description: `Outlet Box`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJCND-1`,
    description: `Chrome Center Trim (RCHR)`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `TJRK100`,
    description: `Electric Stove Knob Kit`,
  },
  {
    category: `Range`,
    subcategory: `Misc`,
    partNumber: `WG02A00752`,
    description: `Range Wall Receptacle`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `CH0213`,
    description: `Bake Element, 2500w (9750213)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DP8413`,
    description: `8" Chrome Drip Pan (316048413)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `DP8414`,
    description: `6" Chrome Drip Pan (316048414)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `ES10027`,
    description: `8" Infinite Switch (WB24T10027)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `ES10029`,
    description: `6" Infinite Switch (WB24T10029)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `RA7002`,
    description: `Temperature Probe (316217002)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `SGR414`,
    description: `Ignitor (12400035)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `SGR5066`,
    description: `Ignitor (5303935066)`,
  },
  {
    category: `Range`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `SGR9402`,
    description: `Igniter (316489402)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `57-R600A-14`,
    description: `Refrigerant Grade Isobutane`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `981`,
    description: `Super Change Fast & Easy R22 System Retrofit`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `984`,
    description: `SuperSeal SureShot AC/R Leak Stop`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `985`,
    description: `SuperSeal Flex Inject`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `990`,
    description: `Flash Detect Inject`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `991`,
    description: `Super Change Inject`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `992`,
    description: `Boost Juice Inject`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `995`,
    description: `Flex Inject Sealant Total w/UV Dye`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `84DCPLUS`,
    description: `Light, UV, Mini, Seeker`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `87DCPLUS`,
    description: `Light, UV, Max, Seeker`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `89DC`,
    description: `Light, UV, Pocket`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `944KIT`,
    description: `SuperSeal Adv, 1.5 - 5 ton`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `948KIT`,
    description: `SuperSeal Adv, 5 ton+`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `972KIT`,
    description: `SuperSeal Total, 1.5 - 5 ton`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `98084KIT`,
    description: `84-Kit, Flash Mini`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `98087KIT`,
    description: `84-Kit, Flash Maxi`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `983KIT`,
    description: `SuperSeal SureShot`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `993KIT`,
    description: `Boost Juice`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `TJ20122`,
    description: `Sealant/Dye Injection Hose`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `TJ947KIT`,
    description: `Super Seal ACR`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `TJ971KIT`,
    description: `Super Seal Total 3n1`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `TJ973KIT`,
    description: `Dry R Moisture Removal`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Cliplight`,
    partNumber: `TJ980`,
    description: `High Resolution Universal Dye`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFF10BK1`,
    description: `R12 Compressor, 1/4 HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFF10BX`,
    description: `R12 Compressor, 1/4+ HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFF10HBX`,
    description: `R134a Compressor, 1/4+ HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFF11.5BK`,
    description: `R12 Compressor, 1/3 HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFF7.5HBK`,
    description: `R134a Compressor, 1/5+ HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFF8.5BK`,
    description: `R12 Compressor, 1/4 HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFF8.5HBK`,
    description: `R134a Compressor, 1/4 HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFFC60BK`,
    description: `R12 Compressor, 1/5+ HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFFI10HBX`,
    description: `R134a Compressor, 1/3 HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJFFI12HBX`,
    description: `R134a Compressor, 1/3+ HP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Compressors`,
    partNumber: `TJSPC660L`,
    description: `1/5HP Compressor, 660 BTU`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Driers & Access Valves`,
    partNumber: `TJ4000`,
    description: `3/4" Service Drier`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Driers & Access Valves`,
    partNumber: `TJ4007A`,
    description: `1" Drier, Swaged w/Valve`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Driers & Access Valves`,
    partNumber: `TJ4013`,
    description: `1" Drier`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Driers & Access Valves`,
    partNumber: `TJSAV-3`,
    description: `3/16" Access Valve`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Driers & Access Valves`,
    partNumber: `TJSAV-4`,
    description: `1/4" Access Valve`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Icemaker Water Lines`,
    partNumber: `TJ48387`,
    description: `5’ Icemaker Water Line, Braided Stainless Steel (1/4” x OD)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Icemaker Water Lines`,
    partNumber: `TJ48389`,
    description: `10’ Icemaker Water Line, Braided Stainless Steel (1/4” x OD)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Icemaker Water Lines`,
    partNumber: `TJ48392`,
    description: `25’ Icemaker Water Line, Braided Stainless Steel (1/4” x OD)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Icemaker Water Lines`,
    partNumber: `TJ48090`,
    description: `Stainless Steel Supply Connector, 7/8" x 3/8" COMP, 20" Length`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000576`,
    description: `2 NK MS 00.079"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000587`,
    description: `5 NK MS 00.188" OR 3/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000588`,
    description: `6 NK MS 00.250" OR 1/4"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000589`,
    description: `6.5 NK MS 00.256"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000590`,
    description: `7 NK MS 00 .276"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000591`,
    description: `7.5 NK MS 00 .295"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000592`,
    description: `8 NK MS 00.313" OR 5/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000616`,
    description: `4/2 NR MS 00.156" OR 5/32" - .079"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000622`,
    description: `5/4 NR MS 00.197 OR 3/16" - .156" OR 5/32"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000625`,
    description: `6/2 NR MS 00.250" OR 1/4" - .079"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000627`,
    description: `6/2.5 NR MS 00.250 OR 1/4" - .098"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000629`,
    description: `6/4 NR MS 00.250 OR 1/4" - .156" OR 5/32"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000630`,
    description: `6/5 NR MS 00.250" OR 1/4" - .197" OR 3/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000638`,
    description: `7/5 NR MS 00.276" - .197" OR 3/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000654`,
    description: `8/6 NR MS 00.313" OR 5/16" - .250" OR 1/4"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000656`,
    description: `8/6.5 NR MS 00.313" OR 5/16" - .256"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000674`,
    description: `8.5/6 NR MS 00.335" - 1/4"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13000964`,
    description: `6/2 NR AL 00.250" OR 1/4" - .079"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13002949`,
    description: `4/3.2 NR MS 00.156" OR 5/32" - .126" OR 1/8"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13005630`,
    description: `7.5 NK AL 00.295"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13005655`,
    description: `8/7.5 NR AL 00.313" OR 5/16" - .300"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L13005894`,
    description: `8/1.8 NR AL 00.313" OR 5/16" - .071"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Fittings`,
    partNumber: `L14000143`,
    description: `6 NF MS SV 120 MM OR 4.7" Long`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Tools`,
    partNumber: `L13003829`,
    description: `HMRK-VMANUAL Hand Tool w/2 Hinged Handles`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Tools`,
    partNumber: `L13006027`,
    description: `Lokbox`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Tools`,
    partNumber: `L14000208L`,
    description: `R134A Recovery Bag`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Tools`,
    partNumber: `L14000878`,
    description: `Lokprep 65G65G 15ml Bottle`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Tools`,
    partNumber: `L20000200`,
    description: `MB 8 Assembly Jaw Up to 5/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Lokring Tools`,
    partNumber: `L20000201`,
    description: `MB 10 Assembly Jaw 3/8"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJ5311`,
    description: `Condenser Fan Motor, 6W CW Cast Iron  (15311, R5311)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJ5411`,
    description: `Condenser Fan Motor, 9W CW Cast Iron (15411, R5411)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJ90925`,
    description: `Slim Condenser Comb Kit Multi Head`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJR1211`,
    description: `1/150HP Condenser Fan Motor`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJR5090`,
    description: `Condenser Motor, Sub Zero`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJR5211`,
    description: `4W Condenser Fan Motor`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJSM999`,
    description: `Evaporator Fan Motor w/Multi-Mount Kit`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJUEFM-1`,
    description: `Universal Evaporator Fan Motor Kit`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Motors`,
    partNumber: `TJWIFM-1`,
    description: `Universal Evaporator Fan Motor Kit`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `TJ84042`,
    description: `Quick Connect Union, 1/4" OD`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `TJ84049`,
    description: `Quick Connect Union, 3/8" OD x 1/4" OD`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `TJ84050`,
    description: `Quick Connect Union, 3/8" OD`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `TJ84052`,
    description: `Quick Connect Tee, 1/4" OD`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `TJ84055`,
    description: `Quick Connect Elbow, 1/4" OD`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `TJ84056`,
    description: `Quick Connect Elbow, 3/8" OD`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `TJSPFU516`,
    description: `Union Connector, 5/16" - 5/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `WP2300868`,
    description: `Union Connector, 5/16" - 5/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Quick Connects`,
    partNumber: `WR01F02845`,
    description: `Union Connector, 5/16" - 5/16"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `50039`,
    description: `Gas Leak Detector, 8oz Bottle`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `70088`,
    description: `1/4” Tube Piercing Plier`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ11575`,
    description: `Heat Seal Stik, 3/8oz (95430)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ63010`,
    description: `D.O.T. Supply Tank, 50lbs`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70027`,
    description: `Mini Tube Cutter, 1/8" - 5/8"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70033`,
    description: `Heavy Duty Tube Cutter, 1/8" - 1 1/8"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70040`,
    description: `All-in-One Swaging Punch, Chrome Finished`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70045`,
    description: `Sand Cloth, 1 1/2" x 5 yds`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70048`,
    description: `Swaging Punches (Pack of 5)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70051`,
    description: `Flaring Tool - Standard`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70057-A`,
    description: `Eccentric Cone Flaring Tool w/6 Sizes & Plastic Box`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70069-A`,
    description: `180° 4-in-1 Bender (3/16", 1/4", 5/16" & 3/8" OD)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70076`,
    description: `Sprin Style Tube Bender Set (5pc)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ70083`,
    description: `Pinch Off Locking Pliers`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJBPV-21`,
    description: `Piercing Valve (1/2" & 5/8")`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJBPV-31`,
    description: `Piercing Valve (1/4", 5/16" & 3/8")`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJCD2035`,
    description: `Charging Hose Adapter`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJCD4311`,
    description: `Instatap Tube Pierce Pliers`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJCD4314`,
    description: `TLPPX Replacement Tip`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJCD5512`,
    description: `1/2" Saddle Valve (4/pkg)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJCD5516`,
    description: `5/16" Saddle Valve (6/pkg)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `22725`,
    description: `Patriot 2-Valve Manifold with Propane Gauges`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `59161`,
    description: `R410A, R22, R404A 2-Way Brass Manifold Gauge Set w/ R410A Hoses and Standard 1/4” SAE Fittings`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `04-22733-18`,
    description: `Patriot 2-Valve Brass Manifold`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `57-HC-KIT`,
    description: `Valve Tool Kit w/Carrying Case`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJSS45`,
    description: `Silver Solder, 1oz .60-205`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `57-HC-VLV`,
    description: `R600 Valves`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `57-R600A-15`,
    description: `15lbs R600A`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `93636-RB`,
    description: `2 Aluminum Manifold w/1.6 Gauge Bar/PSI/C 80mm Diameter & 3 90cm Hoses (R600A, R290, R1270)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `DS-20000`,
    description: `Atlas Refrigerant Charging Scale`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `DS-20000S`,
    description: `Wireless Atlas Refrigerant Charging Scale`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `LDC-4000`,
    description: `Combustible Gas and HC Refrigerant Leak Detector`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ33636`,
    description: `36" Manifold w/Hoses, R22`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ40360`,
    description: `60" Standard Hose Set w/Standard Fittings`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ55-U7001`,
    description: `16oz Charging Glass, R134`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ55200`,
    description: `Electronic Leak Detector`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ56136`,
    description: `Manifold w/36" Hose, R134`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJ62010`,
    description: `Recovery Tank, 30lbs`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TJR410A`,
    description: `30lbs R410`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Tools`,
    partNumber: `TRS21`,
    description: `Sparkless Ignition Proof Recovery Machines`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `00640565`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `00750673`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `11028820`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `5231JA2006F`,
    description: `LT600P`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `836848`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `842802`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `847200`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `ADQ36006101`,
    description: `LT700P`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `ADQ72910901`,
    description: `LT500P`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `ADQ73613401`,
    description: `LT800P`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `ADQ74793501`,
    description: `LT1000P`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR1RXD1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR2RXD1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR3RXD1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR4RXD1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR5RXD1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR6D1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR7D1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EDR8D1B`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EPTWFU01C`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `EWF01C`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `ULTRAWFC`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WF2CBC`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WF3CBC`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WFCB`,
    description: `n/a`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WG03F00675`,
    description: `GSWF`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WG03F00676`,
    description: `MSWF`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WG03F00835`,
    description: `MWF/MWFP`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WG03F04947`,
    description: `RPWFE`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Filters`,
    partNumber: `WR01F04493`,
    description: `XWF`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Lines`,
    partNumber: `TJC25`,
    description: `25’ Water Line Installation Kit (1/4” Copper Tubing w/Valve)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Lines`,
    partNumber: `TJIMIK-01-25-P5`,
    description: `25’ Water Line Installation Kit (1/4” Plastic Tubing Connects to 1/2” water supply line)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Water Lines`,
    partNumber: `TJPT25`,
    description: `25’ Water Line Installation Kit (1/4” Plastic Tubing w/Valve)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ335`,
    description: `Refrigerator/Freezer Thermometer`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ4007`,
    description: `1" Valve Drier`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ41036`,
    description: `10' Stainless Steel Icemaker Connector, 1/4" x 1/4"`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ42010-10`,
    description: `1/4" SAE Gasket for Charging Hoses`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ5109`,
    description: `Condenser Fan Motor, 2W CW 1550 Cast Iron (SM5109)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ60461N`,
    description: `10" Filter w/Fittings`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ719-501`,
    description: `Defrost Timer, 6hr 21min`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ90032`,
    description: `Vacuum Pump Oil, 1qt  ( 90032-6)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ90UET120`,
    description: `Universal Electronic Timer`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJIC102`,
    description: `1/20 HP to 1/3 HP Compressor Relay`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJSPN1111AD`,
    description: `Universal Defrost Timer, 6hr 21min`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJWM8578`,
    description: `Ice Machine Cleaner, 500ml`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `93001`,
    description: `Glide-n-Guard Floor Protector`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `TJ25HP-01-1`,
    description: `Refrigerator/Freezer Thermometer (125)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `Misc`,
    partNumber: `8003RP`,
    description: `15’ Water Line Installation Kit (1/4” Copper Tubing w/Valve)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `RIM0022`,
    description: `Ice Maker (W10300022)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `SM10307`,
    description: `Evaporator Fan Motor (WR60X10307)`,
  },
  {
    category: `Refrigerator`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `WV2603`,
    description: `Water Valve (242252603)`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0090`,
    description: `WSF-4 Torch Kit Soft-Flame, B Tank`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0100`,
    description: `A-2 Air Acetylene Torch Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0101`,
    description: `A-3 Air Acetylene Torch Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0102`,
    description: `A-5 Air Acetylene Torch Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0545`,
    description: `D-1 Dual Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0551`,
    description: `V-1 Single Flame Oxy-Acetylene Torch Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0554`,
    description: `VM-J Mixer Adaptor, P`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0555`,
    description: `VM-1 Mixer Adaptor, P`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0725`,
    description: `AR-B B Tank Regulator`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0813`,
    description: `245-02P Nitrogen Type R Regulator`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0818`,
    description: `PL-5A Tip Swirl, Air Acetylene, Self Lighting`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0849`,
    description: `NFM-TT Nitrogen Flow Meter`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0850`,
    description: `ST-33 Self-Igniting Propane And MAPP® Torch Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0851`,
    description: `STK-99 Torch Swirl, MAP-Pro/LP Gas, Self Lighting`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0874`,
    description: `PL-3A Tip Swirl, Air Acetylene, Self Lighting`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-0875`,
    description: `GP250-500-580 500 Nitrogen Purge Regulator`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-1059`,
    description: `3A-TE Air Acetylene Replacement Tip End`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-1090`,
    description: `AH-12 Acetylene Torch Hose`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-1200`,
    description: `AG-1 Gauge`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-1282`,
    description: `ST-11 Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-1297`,
    description: `TX503 Torch Swirl, MAP-Pro/LP Gas, Self Lighting`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-1321`,
    description: `CST-PT Oxy/Acetelyne Welding Braze Kit`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0386-1403`,
    description: `Portable Torch Kit`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `0916-0122`,
    description: `MPT-1 Map-Pro Tank`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `245-02P`,
    description: `Nitrogen Type R Regulator`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `245-03P`,
    description: `Nitrogen Purge Regulator`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `A-3`,
    description: `Acetylene Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `A-5`,
    description: `Acetylene Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `AH-12`,
    description: `12' x 3/16" Acetylene Hose`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `AR-B`,
    description: `Acetylene Regulator B`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `AR-MC`,
    description: `Acetylene Regulator MC`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `BTMCR`,
    description: `MC-B Tank Adapter`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `MCT`,
    description: `MCT B-MC Tank Adapter`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `PL-5A`,
    description: `1/4" Proline Tip`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `PL-5ADLX-MC`,
    description: `Torch Kit Swirl, for MC Tank, Air Acetylene`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `TJ0386-0335`,
    description: `X-3B Air Acetylene Torch Outfit`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `TJ0386-0561`,
    description: `PL-812 Proline Torch Shield`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `TJ0386-0813`,
    description: `245-02P Nitrogen Type R Regulator`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `VW-2`,
    description: `Wrapper Tip, Oxy/Acetylene (0386-0580)`,
  },
  {
    category: `TurboTorch`,
    subcategory: `TurboTorch`,
    partNumber: `X-6MC`,
    description: `Air Acetylene Kit (0386-0339)`,
  },
  {
    category: `Washer`,
    subcategory: `Drain Hoses`,
    partNumber: `TJSSD-6`,
    description: `6’ Drain Hose (Flexible Polyflo, Gooseneck, fits 1”, 1-1/8” & 1-1/4”)`,
  },
  {
    category: `Washer`,
    subcategory: `Drain Hoses`,
    partNumber: `TJ76WDH`,
    description: `6' Drain Hose, Corrugated`,
  },
  {
    category: `Washer`,
    subcategory: `Drain Hoses`,
    partNumber: `TJHYP38`,
    description: `English 12” Y Style Mixer Hose`,
  },
  {
    category: `Washer`,
    subcategory: `Fill Hoses`,
    partNumber: `TJ3802MF`,
    description: `2' Fill Hose`,
  },
  {
    category: `Washer`,
    subcategory: `Fill Hoses`,
    partNumber: `TJ3805FE`,
    description: `5' Fill Hose, 90° Elbow`,
  },
  {
    category: `Washer`,
    subcategory: `Fill Hoses`,
    partNumber: `TJ3805FF`,
    description: `5' Fill Hose, Single`,
  },
  {
    category: `Washer`,
    subcategory: `Fill Hoses`,
    partNumber: `TJ3806FE`,
    description: `6'  5' Fill Hose, 90° Elbow (60F90)`,
  },
  {
    category: `Washer`,
    subcategory: `Fill Hoses`,
    partNumber: `TJ3806FF`,
    description: `6' Fill Hose`,
  },
  {
    category: `Washer`,
    subcategory: `Fill Hoses`,
    partNumber: `TJ3808FE`,
    description: `8' Fill Hose, 90° Elbow  (WH41M49)`,
  },
  {
    category: `Washer`,
    subcategory: `Fill Hoses`,
    partNumber: `TJ3810FF`,
    description: `10' Fill Hose  (WH41M25)`,
  },
  {
    category: `Washer`,
    subcategory: `Rubber Hoses`,
    partNumber: `TJHK10`,
    description: `10’ x 2 Rubber Connection Hose w/Washers (SHK10)`,
  },
  {
    category: `Washer`,
    subcategory: `Rubber Hoses`,
    partNumber: `TJHK4`,
    description: `4’ x 2 Rubber Connection Hose  w/Washers (SHK4)`,
  },
  {
    category: `Washer`,
    subcategory: `Rubber Hoses`,
    partNumber: `TJHK5`,
    description: `5’ x 2 Rubber Connection Hose Kit w/Washers (SHK5)`,
  },
  {
    category: `Washer`,
    subcategory: `Rubber Hoses`,
    partNumber: `TJHK6`,
    description: `6’ x 2 Rubber Connection Hose Kit w/Washers (SHK6)`,
  },
  {
    category: `Washer`,
    subcategory: `Rubber Hoses`,
    partNumber: `TJHK8`,
    description: `8’ x 2 Rubber Connection Hose w/Washers (SHK8)`,
  },
  {
    category: `Washer`,
    subcategory: `Stainless Steel Hoses`,
    partNumber: `TJ48370`,
    description: `4’ x 2 Braided Stainless Steel Hose Kit w/Washers (SHK4)`,
  },
  {
    category: `Washer`,
    subcategory: `Stainless Steel Hoses`,
    partNumber: `TJ48371`,
    description: `5’ x 2 Braided Stainless Steel Hose Kit w/Washers (SHK5)`,
  },
  {
    category: `Washer`,
    subcategory: `Stainless Steel Hoses`,
    partNumber: `TJ48372`,
    description: `6’ x 2 Braided Stainless Steel Hose Kit w/Washers (SHK6)`,
  },
  {
    category: `Washer`,
    subcategory: `Stainless Steel Hoses`,
    partNumber: `TJ48378`,
    description: `6’ x 2 Braided Stainless Steel Hose Kit w/Washers 90°Elbow`,
  },
  {
    category: `Washer`,
    subcategory: `Washer Miscellaneous`,
    partNumber: `PMLAV01234`,
    description: `Washer Tray (WX7X1)`,
  },
  {
    category: `Washer`,
    subcategory: `Washer Miscellaneous`,
    partNumber: `TJCW-151`,
    description: `Universal Washer Inlet Valve`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `ES1800`,
    description: `Lid Switch (134101800)`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `ES247`,
    description: `Lid Switch (3949247)`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `ES8084`,
    description: `Lid Switch (8318084)`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `LB2788`,
    description: `Washer Belt (WH1X2788)`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `LP10279`,
    description: `Pressure Switch (WH12X10279)`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `LP2119`,
    description: `Door Gasket (8182119)`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `LP785`,
    description: `Clutch (285785)`,
  },
  {
    category: `Washer`,
    subcategory: `NON OEM SUPCO`,
    partNumber: `LP8000`,
    description: `Drain Pump (137108000)`,
  },
];
